### ISSUE TITLE
Rare EOFException in SerializedPersistence on recompile

### ISSUE THREAD

**Issue by PseudoKnight** [EngineHub/CommandHelper#1279]
I don't recall ever encountering this before.

```
[08:11:56] [SerializedPersistenceQueue-2/WARN]: java.io.EOFException
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream$BlockDataInputStream.readUnsignedShort(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream$BlockDataInputStream.readUTF(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readString(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readObject0(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.util.HashMap.readObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readSerialData(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readObject0(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.io.ObjectInputStream.readObject(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at com.laytonsmith.persistence.SerializedPersistence$1.call(SerializedPersistence.java:106)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:11:56] [SerializedPersistenceQueue-2/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by PseudoKnight** [comment]
Closing because it's redundant to issue #1341, and the conversation is longer there.
