### ISSUE TITLE
Error occurred while enabling CommandHelper v1332-1b25c4f

### ISSUE THREAD

**Issue by LadyCailin** [EngineHub/CommandHelper#557]
CMDHELPER-2606 - Reported by joy on 2013-01-26 20:40:06 UTC

Full error below.

This error only appears on recent Spigot builds (439 is fine). I am just reporting it here as well, told md5, as I don't know who is to blame here.

2013-01-26 21:35:56 [INFO] [CommandHelper] Enabling CommandHelper v1332-1b25c4f
2013-01-26 21:35:56 [SEVERE] Error occurred while enabling CommandHelper v1332-1b25c4f (Is it up to date?)
java.lang.IllegalAccessError: tried to access method org.mcstats.Metrics$Graph.<init>(Ljava/lang/String;Lorg/mcstats/Metrics$1;)V from class org.mcstats.Metrics
        at org.mcstats.Metrics.<init>(Metrics.java:109)
        at com.laytonsmith.commandhelper.CommandHelperPlugin.onEnable(CommandHelperPlugin.java:109)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:458)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
        at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:308)
        at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:290)
        at net.minecraft.server.v1_4_R1.MinecraftServer.j(MinecraftServer.java:326)
        at net.minecraft.server.v1_4_R1.MinecraftServer.e(MinecraftServer.java:305)
        at net.minecraft.server.v1_4_R1.MinecraftServer.a(MinecraftServer.java:264)
        at net.minecraft.server.v1_4_R1.DedicatedServer.init(DedicatedServer.java:149)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:404)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

**Comment by LadyCailin** [comment]
Comment by joy on 2013-02-01 16:38:57 UTC

Any help please? Can't update server due to this...

**Comment by LadyCailin** [comment]
Comment by jb_aero on 2013-02-02 21:44:22 UTC

Turn off metrics? someone else had this error last night

**Comment by LadyCailin** [comment]
Comment by joy on 2013-02-05 12:28:11 UTC

How? there's no setting in preferences.txt

**Comment by LadyCailin** [comment]
Comment by jb_aero on 2013-02-08 18:33:28 UTC

turn off metrics globally in plugins/PluginMetrics/config.yml

**Comment by LadyCailin** [comment]
Comment by joy on 2013-02-09 08:50:29 UTC

Already have "opt-out: true" set in that file, since forever, so that's not a fix!

**Comment by LadyCailin** [comment]
Comment by wizjany on 2013-02-09 09:36:08 UTC

this is a spigot issue, i think it was fixed recently

**Comment by LadyCailin** [comment]
Comment by joy on 2013-02-20 11:53:34 UTC

Yup fixed at last.
